[build]
  publish = "build"
  command = "npm run build"
  node_version = "16"


[context.production.environment]
  NODE_ENV = "production"
[build.environment]
  NODE_OPTIONS = "--openssl-legacy-provider"